### ISSUE TITLE
Funcionalidades

### ISSUE THREAD

**Issue by GabrielaBoaventura** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t5-Mentally#18]
![Avaliacao](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t5-pmv-ads-2023-1-e1-proj-web-t5-mente/assets/123635086/7cbca7d9-ca33-4ef7-bd68-d9e84008442e)
![9](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t5-pmv-ads-2023-1-e1-proj-web-t5-mente/assets/127910122/67f9bda7-95e2-46ed-9600-e2d5918c5aff)
![1](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t5-pmv-ads-2023-1-e1-proj-web-t5-mente/assets/127910122/2bc919cf-02bd-4ff9-8adb-e614d0e030c6)
![2](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t5-pmv-ads-2023-1-e1-proj-web-t5-mente/assets/127910122/4ead3b63-79cd-43ba-b6d3-6c322cba5dab)
![3](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t5-pmv-ads-2023-1-e1-proj-web-t5-mente/assets/127910122/cc3ae2a8-2afc-445a-b1b9-7b8442b8a566)
![4](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t5-pmv-ads-2023-1-e1-proj-web-t5-mente/assets/127910122/c763f910-5477-4b95-a2e9-b31f06382471)
![5](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t5-pmv-ads-2023-1-e1-proj-web-t5-mente/assets/127910122/5ae8c1d6-48df-4909-8a63-d5ddee0bed4a)
![6](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t5-pmv-ads-2023-1-e1-proj-web-t5-mente/assets/127910122/1fc37561-2398-4b07-be3f-e1c9b1c7d15d)
![0](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t5-pmv-ads-2023-1-e1-proj-web-t5-mente/assets/127910122/d4a1b515-7e03-4d0b-acfd-ddf958ecad13)
![historico](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t5-pmv-ads-2023-1-e1-proj-web-t5-mente/assets/123635086/c6677fca-d90d-4233-8f21-88a9fe2c28ef)

**Comment by AlvaroGR028** [comment]
Imagens substituídas para a pasta correta.
